config/routes.rb
Epicprose::Application.routes.draw do

  devise_for :users
  root to: "stories#index"

  resources :stories, only:[:new,:index,:show,:create,:destroy]  do
    resources :chapters, only:[:new,:create,:destroy]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :story
  validates_presence_of :body

  def self.random_category
    Category.limit(1).offset(rand(Category.count)).first
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :story
  belongs_to :user

  validates :body, presence: true, length: {
    maximum: 120,
    minimum: 2
  }
  validates_associated :story, message: "Only 6 chapters allowed"

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates_presence_of :uri
  validates_format_of :uri,
    with: /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/ ,
    message: "Valid URL is required"

  def self.random_image
    Image.limit(1).offset(rand(Image.count)).first.uri
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  has_many :users, through: :story_roles
  has_many :story_roles
  has_one  :category

  validate :chapter_limit_not_reached, on: :update
  validates :title,
    presence: true,
    length: {
      minimum: 2,
      maximum: 120,
      too_short: "Must have at least 2 characters",
      too_long: "Must have at most 120 characters"
    }

  before_create :before_create
  before_save :before_save

private

  def before_create
    self.category = Category.random_category
    self.picture_url = Image.random_image
  end

  def chapter_limit_not_reached
    errors.add(:story, "Cannot have more than 6 chapters") if chapters.size > 6
  end

  def before_save
    if chapters.size == 6
      self.completed = true
    end
  end

end

app/models/story_role.rb
class StoryRole < ActiveRecord::Base
 belongs_to :user
 belongs_to :story

 def assign_role( role )
   self.role =  role
   self.save
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :stories, through: :story_roles
  has_many :story_roles
  has_many :chapters

  def get_friends
    friends = []
    self.stories.each do |story|
      story.users.each do |user|
        friends << user.email if user.email != self.email
      end
    end
    friends.uniq
  end

  def get_user_stories
    if self.stories.empty?
      stories = []
    else
      stories = self.stories
    end
    stories
  end
end

app/models/writing_prompt.rb
class WritingPrompt < ActiveRecord::Base
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter,  only:  [ :show, :edit  ]

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new( chapter_params )
    story = Story.find( params[:story_id] )

    @chapter.user = current_user
    story.chapters << @chapter
    story.turn = get_other_user( current_user, story )

    respond_to do |format|
      if @chapter.save && story.save
        ChapterMailer.new_chapter_email( story, @chapter ).deliver
        format.html { redirect_to story_path( story.id ),
                      notice: 'Chapter was successfully created.' }
        format.json { render action: 'show',
                      status: :created, location: [ :story, @chapter ] }
      else
        format.html { render action: 'new' }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def chapter_params
    params.require( :chapter ).permit( :body )
  end

  def set_chapter
    @chapter = Story.find( params[:story_id]).chapters.find(params[:id] )
  end

  def get_other_user( user, story )
    role = StoryRole.where( "story_id = :story_id AND user_id != :user_id",
                          { story_id: story.id, user_id: user.id} ).first
    role.user.id.to_i
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [ :show, :edit, :update, :destroy ]

  def index
    @stories = current_user.get_user_stories
  end

  def show
  end

  def new
    @story = Story.new
    @friends = current_user.get_friends
  end

  def create
    co_author = get_co_author
    redirect_to new_story_path, alert: "valid co-author email required" and return unless co_author 

    @story = Story.new( story_params )
    @story.turn = current_user.id

    respond_to do |format|
      if @story.save && co_author
        current_user.stories  << @story
        co_author.stories     << @story
        assign_story_roles( co_author )

        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  private

    def set_story
      @story = Story.find( params[:id] )
    end

    def get_co_author
      user = User.where( email: params[:co_author] ).first
      user = nil if user && user.id == current_user.id
      user
    end

    def story_params
      params.require( :story ).permit( :title, :picture_url )
    end

    def assign_story_roles( co_author )
      role = StoryRole.where( story_id: @story.id, user_id: co_author.id ).first
      role.assign_role( "co_author" )

      role = StoryRole.where( story_id: @story.id, user_id: current_user.id ).first
      role.assign_role( "author" )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def get_co_author( story_id )
    StoryRole.where( story_id: story_id, role: :co_author ).first.user.email
  end

  def get_author( story_id )
    StoryRole.where(story_id: story_id, role: :author).first.user.email
  end

  def get_user_turn( id )
    turn = "Your turn"
    turn =  User.find( id ).email if id != current_user.id
    turn
  end
end

app/views/chapters/new.html.erb
<br/>
<h4>New Chapter </h4>
<%= form_for([:story, @chapter]) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
        <% @chapter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field chapter-field">
    <%= f.text_area :body, required: true, maxlength: 120  %>
  </div>

  <div class="actions">
    <%= f.submit class: "button",value: "Save" %>
    <%= link_to 'Cancel', story_path(params[:story_id]), class: "button secondary" %>
  </div>
<% end %>

app/views/layouts/_alerts.html.erb
  <% if notice %>
    <script type="text/javascript" charset="utf-8">
      window.setTimeout(function() { $(".alert-box").fadeOut(500); }, 3000);
    </script>
    <div data-options="animation:fadeout;" data-alert class="alert-box success">
      <%= notice %>
      <a href="" class="close">×</a>
    </div>
  <% end %>
  <% if alert %>
    <script type="text/javascript" charset="utf-8">
      window.setTimeout(function() { $(".alert-box").fadeOut(500); }, 3000);
    </script>
    <div data-options="animation:fadeout;" data-alert class="alert-box alert">
      <%= alert %><a href="" class="close">×</a>
    </div>
  <% end %>

app/views/layouts/_topbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="<%= root_path %>">Epic Prose <span class="label alert radius">beta</span></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <!--  Right nav section  -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#"><%= current_user && current_user.email %></a>
        <ul class="dropdown">
          <% if user_signed_in? %>
            <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          <% else %>
            <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Epic Prose" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/topbar' %>
  <%= render 'layouts/alerts' %>

  <div class="row main">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>

  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize( @story.errors.count, "error" ) %> prohibited this story from being saved:</h2>
      <ul>
        <% @story.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="title"> Title
      <%= f.text_field :title, required: true, maxlength: 120 %>
    </label>
  </div>

  <div class="field">
    <label for="co_author">Co Author
      <%= email_field_tag :co_author, nil, required: true, maxlength: 120  %>
    </label>
  </div>

  <div class="actions">
    <%= f.submit class: "button disableHoverColor" %>
  </div>
<% end %>

app/views/stories/_friends_list.html.erb
<div class="panel friends_list">
  <p class="lead">Your Co-Authors</p>
  <ul class="fa-ul">
    <% if @friends %>
      <% @friends.each do |friend| %>
        <%= content_tag(:li, fa_icon("user", text: friend, class:"fa-li") ) %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/stories/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h2 class="left"><%= t('stories_page_headline') %></h2>
    <%= link_to 'New Story', new_story_path, class: "button right disableHoverColor" %>
    <!-- <span class="paginate&#45;thing"><%# paginate @stories %></span> -->
  </div>
</div>
<div class="row">
  <div class="large-12 large-centered columns ">
    <table class="responsive">
      <thead>
        <tr>
          <th width="300">Title</th>
          <th width="300">Category</th>
          <th width='500'>Image</th>
          <th width='10'>Chapters</th>
          <th width='100'>Turn</th>
          <th width='100'></th>
          <th width='100'></th>
        </tr>
      </thead>
      <tbody>
        <% @stories.each do |story| %>
          <tr>
            <td><h3><%= truncate(story.title, length: 20) %></h3></td>
            <td><h3><%= story.category.body %></h3></td>
            <td class="story_index"><img src="<%= story.picture_url %>" alt="Random picture"/></td>
            <td>
               <% if story.completed %>
                  <p class="label success">completed</p>
               <% elsif story.chapters.length == 0 %>
                  <p class="label alert"><%= story.chapters.length %></p>
               <% else %>
                  <p class="lead"><%= story.chapters.length %></p>
               <% end %>
            </td>
            <td>
               <%= get_user_turn( story.turn ) unless story.completed %>
            </td>
            <td> <%= link_to 'Show', story, class: "button small disableHoverColor" %> </td>
            <td>
              <%= link_to 'Delete', story, method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "button secondary small" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stories/new.html.erb
<h1>Start a New Story</h1>
<hr />
<div class="row">
  <div class="large-8 columns">
    <%= render 'form' %>
  </div>
  <div class="large-4 columns">
    <%= render 'friends_list' %>
  </div>
</div>

<%= link_to 'Back', stories_path, class: "button small disableHoverColor secondary" %>

app/views/stories/show.html.erb
<h2><%= @story.title %></h2>
<p><strong>Category:</strong> <%= @story.category.body %></p>

<div>
  <img src="<%= @story.picture_url %>" alt="Randomly Assigned Image" />
</div>

<p><strong>Co Author:</strong> <%= get_co_author( @story.id )%></p>
  <% if !@story.completed  %>
    <p><strong>Turn:</strong> <%= get_user_turn( @story.turn ) %></p>
  <% else %>
    <span class="label success">completed</span>
  <% end %>
<hr />
<h3>Chapters</h3>
<table>
  <thead>
    <tr>
      <th>user</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @story.chapters.each do |chapter| %>
      <tr>
        <td><h4><%= chapter.user.email %></h4></td>
        <td><h4><%= chapter.body %></h4></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if !@story.completed && ( @story.turn == current_user.id ) || @story.turn.nil? %>
  <%= link_to 'New Chapter', new_story_chapter_path(@story.id), class: "button disableHoverColor" %> 
<% end %>
<%= link_to 'Back', stories_path , class: "button alert disableHoverColor"%>